#正式环境下的数据库(暂时还未建库)
spring:
  datasource:
    url: jdbc:mysql://182.254.242.96/          ?characterEncoding=utf-8&serverTimezone=UTC
    username: developer
    password: feidian52.com
    driver-class-name: com.mysql.cj.jdbc.Driver

#设置端口
server :
  port :