#正式环境下的数据库
spring:
  datasource:
    url: jdbc:mysql://localhost/               ?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

#设置端口
server :
  port :

